default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin
  host: localhost
  port: 5432
development:
  <<: *default
  database: lomax_project_development
test:
  <<: *default
  database: lomax_project_test
production:
  <<: *default
  database: lomax_project_production
  username: lomax_project
  password: <%= ENV["LOMAX_PROJECT_DATABASE_PASSWORD"] %>
